### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by buluba89** [ModusVivendi/twitter-contest-bot#1]
Ok i am contacting you and not the original developer because you seem more active at development. 

Can i propose to convert the project to python3 so it has better support for utf8? I converted it with 2to3 and it works fine (it didnt make any changes to be honest). I pushed it to my fork if you wanna see

Thanks a lot for the hard work !

**Comment by ModusVivendi** [comment]
I merged your changes, and then cloned this to a new (not forked) repository since it diverges so much from the original.
